Add broot command to fuzzy find files

diff --git a/.config/lf/lfrc b/.config/lf/lfrc
--- a/.config/lf/lfrc
+++ b/.config/lf/lfrc
@@ -144,6 +144,19 @@ cmd copyto ${{
 	notify-send "lf" "📋 Fichero(s) copiados a $dest"
 }}
 
+cmd broot ${{
+	# You need to manually close broot printing the
+	# selected path with :print-path or :pp. You may
+	# want to configure broot keybindings
+	selected="$(broot)"
+	if [ -d "$selected" ]; then
+		lf -remote "send ${id} cd \"${selected}\""
+	elif [ -e "$selected" ]; then
+		lf -remote "send ${id} select \"${selected}\""
+	else
+		>&2 printf "Could not select %s\n" "${selected}"
+	fi
+}}
 
 cmd zlua %{{
 	lf -remote "send ${id} cd \"$(z.lua -e $*)\""
